### PR TITLE
fix: validation of schema begin after testing result (#7)

### LINKED ISSUE #7: Validation of schema begin after testing result
If u run test, validation of schema begin after testing result.

1. run command 
```
$ gulp test
```
2. See error
image

Please, fix it.

### PR DESCRIPTION
**Pull request by svoboda-rabstvo**
Closes #7

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -100,34 +100,38 @@ const static = () => gulp
...
+                        log.info(`OK: ${schema.description} ${test.description}`);
                     } else {
-                        log(`ERROR: ${test.data.$ref}`);
-                        log(`MESSAGE: ${error.errors[0].message}`);
-                        log(`SCHEMA PATH: ${error.errors[0].schemaPath}`);
+                        log.error(`FAIL: ${schema.description} ${test.description}`);
+                        log.error(`FILE: ${test.data.$ref}`);
+                        log.error(`MESSAGE: ${error.errors[0].message}`);
+                        log.error(`SCHEMA PATH: ${error.errors[0].schemaPath}`);
                         process.exitCode = 1;
```
Comment (xferra) [inline gulpfile.js]: Do we still need it?

Comment (xferra) [reply gulpfile.js]: @svoboda-rabstvo so?

Comment (svoboda-rabstvo) [reply gulpfile.js]: Yes, we need it.
